### PR TITLE
Add backup topic

### PR DESCRIPTION
**Pull request by klingtnet**

### CODE REVIEW

**Comment by heyLu** [comment]
I think a general backup session would be more appropriate.  Especially if it provides concrete suggestions.  ("Use `rsync` and let me explain my config" is defined to be concrete enough. :))

**Comment by klingtnet** [comment]
My intention was to speak about backup in general, or to try different ways. Take for example a full disk backup via dd{,_rescue} or the backup of `/home/ using`rsync`. What are the pros and cons?

**Comment by heyLu** [comment]
That sounds good, can you update the description to match that?  Currently it sounds a bit like "backup with docker first, then maybe some general stuff".

**Comment by klingtnet** [comment]
How about [this](https://github.com/klingtnet/dottt.github.io/commit/2d4b5075d8862837b769d2820bb03de3b8d0f97d)?

**Comment by heyLu** [comment]
Thanks!

Looking forward to your talk... :)

**Pull request merged**
